#!/usr/bin/env bash

[ -z $1 ] && TIMES=5|| TIMES=$1
#location="/Users/steve/Library/CloudStorage/iCloud Drive/Documents/GitHub/macos-desktop"
location="/Users/steve/Developer/GitHub/macos-desktop"

if [ ! -h /Library/Desktop\ Pictures/Solid\ Colors ]; then
	sudo sudo ln -s /System/Library/Desktop\ Pictures/Solid\ Colors /Library/Desktop\ Pictures/Solid\ Colors
fi

rm "$location"/set-desktop-catalina-tests.txt

echo -e "Randomly generated by $0 using Catalina Beta build $(system_profiler SPSoftwareDataType | awk '/System Version/ {print $5}')\n" >> "$location"/set-desktop-catalina-tests.txt 

bash "$location"/set-desktop-catalina.sh default
sleep 3

for (( i=1;i<=$TIMES;i++ )); do 
	RANDNUM=$((1 + RANDOM % $(wc -l <  "$location"/desktop-images.txt)))
	SELECTION=$(sed ''$RANDNUM'!d' "$location"/desktop-images.txt)
	#ls "$SELECTION"
	bash "$location"/set-desktop-catalina-tests.sh "$SELECTION" $i $TIMES
done

#bash "$location"/set-desktop-catalina-tests.sh  catalina
#bash "$location"/set-desktop-catalina-tests.sh  light
#bash "$location"/set-desktop-catalina-tests.sh  dark
#bash "$location"/set-desktop-catalina-tests.sh  mojave
#bash "$location"/set-desktop-catalina-tests.sh  mojave-light
#bash "$location"/set-desktop-catalina-tests.sh  mojave-dark
#bash "$location"/set-desktop-catalina-tests.sh  solar
